# Generated by Django 2.1 on 2019-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='operacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
