# Generated by Django 3.0.5 on 2021-02-23 14:23

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import easystockApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_apertura', models.BigIntegerField(verbose_name='Monto inicial')),
                ('caja_cierre', models.BigIntegerField(verbose_name='Monto al cierre')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nueva_clasificacion', models.CharField(default='', max_length=100, verbose_name='Clasificación')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombres y Apellidos')),
                ('ci_ruc', models.CharField(max_length=15, verbose_name='C.I./R.U.C.')),
                ('dig_verif', models.IntegerField(blank=True, verbose_name='DIV')),
                ('tel_nro', models.CharField(blank=True, default='', max_length=20, verbose_name='Número de Teléfono')),
                ('direccion', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección part.')),
                ('email', models.EmailField(blank=True, default='', max_length=50, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo_distribuidor', models.CharField(default='', max_length=100, verbose_name='Distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='LibroEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_tipo', models.CharField(max_length=200, verbose_name='Tipo de documento que respalda el Egreso')),
                ('operacion_fecha', models.DateField(max_length=20, verbose_name='Fecha')),
                ('comprobante_timbrado', models.IntegerField(verbose_name='Timbrado')),
                ('comprobante_nro', models.CharField(max_length=20, verbose_name='Número')),
                ('comprobante_condicion', models.CharField(max_length=20, verbose_name='Condición de venta')),
                ('proveedor_tipo_identificacion', models.CharField(max_length=20, verbose_name='Tipo de Identificación')),
                ('proveedor_nro_identificacion', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('proveedor_razon', models.CharField(max_length=200, verbose_name='Nombres y Apellidos o Razón Social')),
                ('gravadas_10', models.IntegerField(verbose_name='Gravadas 10%')),
                ('gravadas_5', models.IntegerField(verbose_name='Gravadas 5%')),
                ('exentas', models.IntegerField(verbose_name='Exentas')),
                ('egreso_tipo', models.CharField(max_length=200, verbose_name='Tipo de Egreso')),
                ('egreso_clasificacion', models.CharField(max_length=500, verbose_name='Clasificación de Egreso')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nueva_marca', models.CharField(default='', max_length=100, verbose_name='Marca')),
                ('clasificacion_x_marca', models.CharField(default='', max_length=100, verbose_name='Clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(default='', help_text='Cerveza, Licor, Cigarrillo, etc.', max_length=50, verbose_name='Clasificación')),
                ('distribuidor', models.CharField(default='', help_text='Cerverpar, etc.', max_length=100, verbose_name='Distribuidor')),
                ('marca', models.CharField(default='', help_text='Pilsen, Beldent, Lucky Strike, etc.', max_length=50, verbose_name='Marca')),
                ('descripcion', models.CharField(help_text="Pilsen'i, Infinity, etc.", max_length=50, verbose_name='Descripción')),
                ('presentacion', models.CharField(help_text='350ml, 1Ltr., etc.', max_length=50, verbose_name='Presentación')),
                ('barcode', models.BigIntegerField(verbose_name='Código de barras')),
                ('etiqueta_opcional', models.CharField(blank=True, default='', help_text='Cualquier otra carateristica', max_length=100, verbose_name='Etiqueta opcional')),
                ('precio_costo', models.PositiveIntegerField(verbose_name='Precio de costo')),
                ('precio_venta', models.PositiveIntegerField(verbose_name='Precio de venta')),
                ('impuesto', models.CharField(default='10', max_length=2)),
                ('stock', djongo.models.fields.EmbeddedField(model_container=easystockApp.models.Stock, verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
                ('productos', djongo.models.fields.EmbeddedField(model_container=easystockApp.models.ProductosPromocion, verbose_name='')),
                ('precio_promocional', models.PositiveIntegerField(default='', verbose_name='Precio promocional')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easystockApp.Producto')),
            ],
        ),
    ]
